---
title: "eds 212 day 2 task"
author: "Peter Menzies"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
```

## First order univariate derivatives

### A

```{r}
fx <- expression(x ^ 2)

df_dx <- D(expr = fx, name = 'x')

x <- 3

eval(expr = df_dx)
```

### B

```{r}
pa <- expression(2 * ((3* a + 2) ^ 4) - 5)

dp_da <- D(expr = pa, name = 'a')

a <- 1.2

eval(expr = dp_da)
```

### C

```{r}
gt <- expression((-4 * t) / (((t ^ 2) + 1) ^ 3))

dg_dt <- D(expr = gt, name = 't')

t <- 0

eval(expr = dg_dt)
```

## Higher order univariate derivatives

```{r}
gz = expression(4.6 - (1.9 * (z ^ 3)))

dg_dz <- D(expr = gz, name = 'z')

dg_dz
```

### ^^ checked by hand - answers match

## Partial Derivatives

```{r}
f_xyz <- expression(2 * (x ^ 2) * y - 3 * x + 1 + 4 * (z ^ 4) * x)

df_dx <- D(expr = f_xyz, 'x')

df_dy <- D(expr = f_xyz, 'y')

df_dz <- D(expr = f_xyz, 'z')
```

## Make some plots

#### Part 1

```{r}
funktion <- function(x) {2.4 * exp(-0.05 * x) * sin(x)}

ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x = x)) + 
  stat_function(fun = funktion)
```

#### Part 2


```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(
    x = "Bill Length (mm)", 
    y = "Bill Depth (mm)",
    title = "Penguin Bill Length vs Bill Depth")
  
```

#### Jitterplot

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter() +
  labs(
    x = "Species",
    y = "Flipper Length (mm)",
    title = "Flipper lengths of three penguin specices"
  )
```


